# Generated by Django 2.1.7 on 2019-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
