# Generated by Django 2.1.7 on 2019-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190310_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('case', models.CharField(blank=True, max_length=150)),
                ('answer', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='polls', to='poll.Question'),
        ),
    ]
