# Generated by Django 2.1.7 on 2019-03-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20190314_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.Poll'),
            preserve_default=False,
        ),
    ]
