# Generated by Django 2.1.7 on 2019-03-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_auto_20190316_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
    ]
