# Generated by Django 2.1.7 on 2019-03-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_auto_20190316_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='is_answered',
            new_name='order',
        ),
    ]
